### ISSUE TITLE
need UMAP and HDBSCAN params in cluster_ids() method

### ISSUE THREAD

**Issue by WalidERRAIS** [nilomr/pykanto#30]
Hi,

I would like to pass UMAP params `(n_neighbors,min_dist) `and HDBSCAN params `(min_cluster_size, min_samples)` to cluster_ids() method.

**Comment by nilomr** [comment]
You would need to expose them so that the `reduce_and_cluster` method can take, for example, two dictionaries with UMAP and HDBSCAN parameters as kwargs that can then be passed to `umap_reduce`  and `hdbscan_cluster`. I'd be _very_ happy to review and merge a pull request with this feature if you want to work on it—It's an easy one, but I haven't got the time to do it myself just now.

**Comment by nilomr** [comment]
@WalidERRAIS have now updated `pykanto` with this change, available via pip - thanks for contributing! Let me know if you run into any issues, and good luck with your research!
