### ISSUE TITLE
Datasets and syllable sharing?

### ISSUE THREAD

**Issue by ArKornreich** [nilomr/pykanto#33]
Hi Nilo!

Thank you so much for all of your help. Everything's running smoothly now!

One more question. Within a dataset, is it possible to look at unit class sharing between individual birds (IDs)? Are the class labels assigned to units with different IDs consistent across the dataset, I mean? 
Additionally, if this is true, if individuals are added to the dataset later, must every unit be reassigned for this to hold true, or can previously-determined classes be preserved and brought forward as new individuals are added? 

Thank you so much! 

Best,

Ar Kornreich

**Comment by ArKornreich** [comment]
Oh, one more thing!

Is it possible to edit the unit classes after the fact, or once they're saved from the app, that's that?

Thank you! Sorry for all the questions!

Best,

Ar Kornreich

**Comment by nilomr** [comment]
Hi Ar,
I'm sorry for not getting back to you sooner.

> Thank you so much for all of your help. Everything's running smoothly now!

Good to hear!

> One more question. Within a dataset, is it possible to look at unit class sharing between individual birds (IDs)? Are the class labels assigned to units with different IDs consistent across the dataset, I mean? Additionally, if this is true, if individuals are added to the dataset later, must every unit be reassigned for this to hold true, or can previously-determined classes be preserved and brought forward as new individuals are added?

This problem is at the heart of data science / ML, and not specific to this library. When you create a lower-dimensional representation of the repertoire of a single bird, it is specific to that bird, and so are any clusters that you define. It is possible to project new data onto the same latent space, see an example with [UMAP](https://umap-learn.readthedocs.io/en/latest/transform.html), but not straightforward. Still, your previously defined cluster memberships will quickly lose any meaning if there is enough variation in the data. Given that there is, your best bet would be to define syllable/note categories for each individual and then compare these between individuals either continuously or by performing clustering on the entire dataset.

**Comment by nilomr** [comment]
> Is it possible to edit the unit classes after the fact, or once they're saved from the app, that's that?

`pykanto` saves them after you are done with each individual or group. If you need to interrupt mid-process, this is not implemented as such, but the library uses pandas dataframes so that users can do whatever they want using familiar syntax. In this case, you could do the following:

1. Pretend like you are done with that ID by pressing 'next', then 'stop app'. Reload the dataset.
- This would normally mean that when you re-start the app you go to the next ID, but if you set `'unit_check'`  to `False` in the relevant rows of `dataset.files` (group by that ID) you can have a go again.

Relevant code so you can see how this is structured:
https://github.com/nilomr/pykanto/blob/35d2218d5ac13a13b3c1457ea68150358be295c3/pykanto/app/main.py#L259
https://github.com/nilomr/pykanto/blob/35d2218d5ac13a13b3c1457ea68150358be295c3/pykanto/app/main.py#L276

2. The app reads the cluster labels from the `'auto_class'` column, so if you want to preserve the `'class_label'` that you have already assigned, you can simply copy the rows of the `'class_label'` column belonging to that ID to the `'auto_class'` column.

Relevant code so you can see what the app is doing internally:
https://github.com/nilomr/pykanto/blob/35d2218d5ac13a13b3c1457ea68150358be295c3/pykanto/app/main.py#L521

3. Launch the app again.

Hope that helps. Trying to categorise over 50 different types of syllables using this method sounds like very challenging!

**Comment by ArKornreich** [comment]
Thank you so much, Nilo! It is indeed challenging, but so long as my work doesn't get reset each attempt it should be at least possible! 

As for your previous answer regarding syllable type classification with multiple individuals, that makes sense, and is something of a relief, as I don't have to worry about processing all individuals at once if I have to work with them all individually and cluster after the fact anyways.

**Comment by nilomr** [comment]
Good luck! Also forgot to say that there is no reason why the server should time out, if you encounter this again would you mind opening a separate issue documenting it so that I can look into it? Cheers, Nilo

**Comment by ArKornreich** [comment]
Will do! I'll keep you posted!

**Comment by ArKornreich** [comment]
Hi Nilo!

Unfortunately I'm still having issues: the app keeps showing what my classes looked liked before I corrected them. Is there something obviously wrong with my code here?


`# ──── SETTINGS ───────────────────────────────────────────────────────────────
DATASET_ID = "FLMF_real"

# PROJECT_ROOT = Path(Repo(".", search_parent_directories=True).working_tree_dir) # Uncomment this line
PROJECT_ROOT = Path(__file__).parent  # Comment this line out

# Will create an empty directory for the raw data as we don't have it
RAW_DATA = Path(PROJECT_ROOT / "data" / "raw" / DATASET_ID)
RAW_DATA.mkdir(parents=True, exist_ok=True)

# Now build the project directories
DIRS = ProjDirs(PROJECT_ROOT, RAW_DATA, DATASET_ID, mkdir=False)

out_dir = DIRS.DATA / "datasets" / DATASET_ID / f"{DATASET_ID}.db"
dataset = load_dataset(out_dir, DIRS)



from bokeh.palettes import Turbo256

dataset.to_csv(DIRS.DATASET.parent, timestamp=False)

# Copy values from 'class_label' to 'auto_class' for the entire dataset
dataset.units['auto_class'] = dataset.units['class_label']
 
dataset.save_to_disk()

# Reset the check status to False for specific units
target_id = 'GRUY'
dataset.files.loc[dataset.files['ID'] == target_id, 'unit_check'] = False

# Save the updated dataset to disk
dataset.save_to_disk()

use_app = True

if use_app:
    # get number of unique auto_class per ID:
    nlabs = dataset.units.groupby("ID").auto_class.nunique().max()
    palette = list(Turbo256)
    dataset.open_label_app(palette=palette)
    dataset.units['auto_class'] = dataset.units['class_label']
    dataset.save_to_disk
    dataset = dataset.reload()
else:
    df = pd.read_csv(DIRS.DATASET.parent / "checked_labels.csv", index_col=0)
    try:
        dataset.data.insert(2, "class_label", df.class_label.astype("string"))
    except ValueError:
        dataset.data["class_label"] = df.class_label.astype("string")
    dataset.save_to_disk()
    
dataset.save_to_disk()`

I'll keep trying in the meantime. Thank you!

**Comment by ArKornreich** [comment]
Oh! Additionally, here's the timeout error:

2024-02-07 11:45:15,486 Starting Bokeh server with process id: 11116
FutureWarning:
    Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
2024-02-07 11:45:25,650 WebSocket connection opened
2024-02-07 11:45:25,652 ServerConnection created
2024-02-07 15:34:53,519 WebSocket connection closed: code=1001, reason=None
2024-02-07 15:35:15,322 WebSocket connection opened
2024-02-07 15:35:15,354 Uncaught exception GET /app/ws (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/app/ws', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\____\miniconda3\Lib\site-packages\tornado\websocket.py", line 938, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\___\miniconda3\Lib\site-packages\tornado\web.py", line 3301, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\___\miniconda3\Lib\site-packages\bokeh\server\views\ws.py", line 149, in open
    raise ProtocolError("Token is expired.")
bokeh.protocol.exceptions.ProtocolError: Token is expired.

**Comment by nilomr** [comment]
> Hi Nilo!
> 
> Unfortunately I'm still having issues: the app keeps showing what my classes looked liked before I corrected them. Is there something obviously wrong with my code here?

As per the instructions above (https://github.com/nilomr/pykanto/issues/33#issuecomment-1930495997 ,1), you should reload the dataset, not save and then reload - that bit may cause issues. But the main problem is that those instructions were incomplete; I forgot to add that you would also have to update the data app. See this gist where I've written a small function to do all of this at once, hope it helps! If it turns out that more people need this I'll add it to the library.

https://gist.github.com/nilomr/a08787feb8f9cdcb0ca502becfb5319b
